Repository apache/camel-quarkus, pull requests merged in 2025-08, with the labels that each got.

#7575 Enable GrpcTest#forwardOnError test
  integration-tests/grpc/src/test/java/org/apache/camel/quarkus/component/grpc/it/GrpcTest.java
Labels: do-not-merge/hold

#7635 Avoid configuring JasyptPropertiesParser unless encrypted properties are detected
  extensions/jasypt/deployment/src/test/java/org/apache/camel/quarkus/component/jasypt/JasyptNoEncryptedPropertiesTest.java
  extensions/jasypt/runtime/src/main/java/org/apache/camel/quarkus/component/jasypt/CamelJasyptConfig.java
  extensions/jasypt/runtime/src/main/java/org/apache/camel/quarkus/component/jasypt/CamelJasyptRecorder.java
Labels: backport/3.15.x, backport/3.20.x

#7657 Add langchain4j-agent JVM only extension
  catalog/pom.xml
  docs/modules/ROOT/examples/components/langchain4j-agent.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/reference/extensions/langchain4j-agent.adoc
  extensions-jvm/langchain4j-agent/deployment/pom.xml
  extensions-jvm/langchain4j-agent/deployment/src/main/java/org/apache/camel/quarkus/component/langchain4j/agent/deployment/Langchain4jAgentProcessor.java
  extensions-jvm/langchain4j-agent/pom.xml
  extensions-jvm/langchain4j-agent/runtime/pom.xml
  extensions-jvm/langchain4j-agent/runtime/src/main/resources/META-INF/quarkus-extension.yaml
  extensions-jvm/pom.xml
  integration-tests-jvm/langchain4j-agent/pom.xml
  integration-tests-jvm/langchain4j-agent/src/main/java/org/apache/camel/quarkus/component/langchain4j/agent/it/Langchain4jAgentResource.java
  integration-tests-jvm/langchain4j-agent/src/test/java/org/apache/camel/quarkus/component/langchain4j/agent/it/Langchain4jAgentTest.java
  integration-tests-jvm/pom.xml
  poms/bom/pom.xml
  poms/bom/src/main/generated/flattened-full-pom.xml
  poms/bom/src/main/generated/flattened-reduced-pom.xml
  poms/bom/src/main/generated/flattened-reduced-verbose-pom.xml
Labels: JVM
