Repository apache/camel-quarkus, pull requests merged in 2025-04, with the labels that each got.

#7212 fixes #7211: disable SshTest#testProducerWithEdDSAKeyType for RHEL8(9)
  integration-tests-support/test-support/src/main/java/org/apache/camel/quarkus/test/DisabledOnRhel.java
  integration-tests-support/test-support/src/main/java/org/apache/camel/quarkus/test/DisabledOnRhelCondition.java
  integration-tests-support/test-support/src/test/java/org/apache/camel/quarkus/test/DisabledOnRhelConditionTest.java
  integration-tests/ssh/src/test/java/org/apache/camel/quarkus/component/ssh/it/SshTest.java
Labels: backport/3.20.x

#7220 Smooks: EDI isn't supported in Camel Quarkus Smooks
  docs/modules/ROOT/pages/reference/extensions/smooks.adoc
  extensions-jvm/smooks/runtime/src/main/doc/usage.adoc
  poms/bom/pom.xml
  poms/bom/src/main/generated/flattened-full-pom.xml
  poms/bom/src/main/generated/flattened-reduced-pom.xml
  poms/bom/src/main/generated/flattened-reduced-verbose-pom.xml
Labels: backport/3.20.x

#7230 Fix jms-artemis-ra module name
  integration-tests/jms-artemis-ra/pom.xml
Labels: backport/3.20.x

#7239 Handle potential for bcel to be present for xalan native mode
  extensions-support/xalan/deployment/src/main/java/org/apache/camel/quarkus/support/xalan/deployment/XalanNativeImageProcessor.java
Labels: backport/3.20.x

#7240 Do not manage com.squareup.okhttp3:mockwebserver
  poms/bom/pom.xml
  poms/bom/src/main/generated/flattened-full-pom.xml
  poms/bom/src/main/generated/flattened-reduced-pom.xml
  poms/bom/src/main/generated/flattened-reduced-verbose-pom.xml
Labels: backport/3.20.x

#7256 Document groovy extension limitations for property placeholders in native mode
  docs/modules/ROOT/pages/reference/extensions/groovy.adoc
  extensions/groovy/runtime/src/main/doc/limitations.adoc
Labels: backport/3.20.x

#7263 fixes #7262: removal of unecessary dependencies to Quarkus AmazonServices
  extensions-support/azure-core-http-client-vertx/deployment/pom.xml
Labels: backport/3.20.x

#7267 Manage smooks transitives
  pom.xml
  poms/bom/pom.xml
  poms/bom/src/main/generated/flattened-full-pom.xml
  poms/bom/src/main/generated/flattened-reduced-pom.xml
  poms/bom/src/main/generated/flattened-reduced-verbose-pom.xml
Labels: backport/3.20.x

#7276 fixes #7275 Jasypt tests fail on FIPS machine
  integration-tests/jasypt/src/test/java/org/apache/camel/quarkus/component/jasypt/it/JasyptFipsModeTestProfile.java
Labels: backport/3.20.x

#7273 Drop Camel http from Knative consumers list
  docs/modules/ROOT/pages/user-guide/kubernetes.adoc
Labels: backport/3.15.x, backport/3.20.x

#7288 Add missing QuarkusTestResource annotations to k8s ConfigMap & Secret reload tests
  integration-tests/kubernetes/src/test/java/org/apache/camel/quarkus/component/kubernetes/it/KubernetesConfigMapContextReloadTest.java
  integration-tests/kubernetes/src/test/java/org/apache/camel/quarkus/component/kubernetes/it/KubernetesSecretContextReloadTest.java
Labels: backport/3.20.x

#7287 Fixes #7286: aws2-s3 tests fail on FIPS
  integration-test-groups/aws2/aws2-s3/src/test/java/org/apache/camel/quarkus/component/aws2/s3/it/Aws2S3Test.java
  integration-tests-support/aws2/src/test/java/org/apache/camel/quarkus/test/support/aws2/Aws2TestResource.java
Labels: backport/3.20.x

#7289 Fix #7280 to check defualt bean only with @Default qualifier
  extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/RuntimeBeanRepository.java
Labels: backport/3.20.x

#7306 [3.20.x] Upgrade to Quarkus CXF 3.20.2
  pom.xml
  poms/bom/src/main/generated/flattened-full-pom.xml
  poms/bom/src/main/generated/flattened-reduced-pom.xml
  poms/bom/src/main/generated/flattened-reduced-verbose-pom.xml
Labels: backport/3.20.x

#7311 Fixes #7211 Enable ssh eddsa test for RHEL
  integration-tests/ssh/README.adoc
  integration-tests/ssh/src/test/java/org/apache/camel/quarkus/component/ssh/it/SshTest.java
Labels: backport/3.20.x

#7318 fixes #7317 Longer interval for azureServiceBus.scheduled
  integration-test-groups/azure/azure-servicebus/src/test/java/org/apache/camel/quarkus/component/azure/servicebus/it/AzureServiceBusTest.java
Labels: test, backport/3.20.x

#7320 Fix dynamic instantiation of Azure HttpResponseException types in native mode
  extensions-support/azure-core/deployment/src/main/java/org/apache/camel/quarkus/support/reactor/netty/deployment/AzureCoreSupportProcessor.java
  extensions/azure-servicebus/deployment/src/main/java/org/apache/camel/quarkus/component/azure/servicebus/deployment/AzureServicebusProcessor.java
  integration-test-groups/azure/azure-eventhubs/src/main/java/org/apache/camel/quarkus/component/azure/eventhubs/it/AzureEventhubsResource.java
  integration-test-groups/azure/azure-eventhubs/src/test/java/org/apache/camel/quarkus/component/azure/eventhubs/it/AzureEventhubsTest.java
  integration-test-groups/azure/azure-key-vault/src/main/java/org/apache/camel/quarkus/component/azure/key/vault/it/AzureKeyVaultResource.java
  integration-test-groups/azure/azure-key-vault/src/test/java/org/apache/camel/quarkus/component/azure/key/vault/it/AzureKeyVaultTest.java
  integration-test-groups/azure/azure-servicebus/src/main/java/org/apache/camel/quarkus/component/azure/servicebus/it/AzureServiceBusResource.java
  integration-test-groups/azure/azure-servicebus/src/test/java/org/apache/camel/quarkus/component/azure/servicebus/it/AzureServiceBusTest.java
  integration-test-groups/azure/azure-storage-blob/src/main/java/org/apache/camel/quarkus/component/azure/storage/blob/it/AzureStorageBlobResource.java
  integration-test-groups/azure/azure-storage-blob/src/test/java/org/apache/camel/quarkus/component/azure/storage/blob/it/AzureStorageBlobTest.java
  integration-test-groups/azure/azure-storage-queue/src/main/java/org/apache/camel/quarkus/component/azure/storage/queue/it/AzureStorageQueueResource.java
  integration-test-groups/azure/azure-storage-queue/src/test/java/org/apache/camel/quarkus/component/azure/storage/queue/it/AzureStorageQueueTest.java
Labels: backport/3.20.x
